spring.application.name=bank
server.port=8080

# JWT
app.jwt.secret=bankAppSecretKeyForJWTTokenGeneration2026012345
app.jwt.expiration=30000

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bank?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/bank
